/// Flutter icons MyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData characters = IconData(0xe900, fontFamily: _kFontFam);
  static const IconData comics = IconData(0xe901, fontFamily: _kFontFam);
  static const IconData creators = IconData(0xe902, fontFamily: _kFontFam);
  static const IconData events = IconData(0xe903, fontFamily: _kFontFam);
  static const IconData series = IconData(0xe904, fontFamily: _kFontFam);
  static const IconData stories = IconData(0xe905, fontFamily: _kFontFam);
}
